FROM node:16.13

WORKDIR /usr/local/app

ENV PORT=4002
ENV NODE_ENV=production
ENV JSON_PRIVATE_KEY=RAIHANLULUSPHASE3

COPY package.json /usr/local/app

RUN npm install -g nodemon

RUN npm install && npm chace clean --force

WORKDIR /usr/local/app/code

COPY . ./

CMD ["npm","run","start"]
