FROM node

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install 
 
COPY . .

ENV NODE_ENV=production
ENV REDIS_CLOUD_PASSWORD=6PWsqLAGbRksFAg9DdHRU40zlRU32tOp:
EXPOSE $PORT

CMD ["npm","run","start"]