FROM node:16.13

WORKDIR /usr/local/app

ENV NODE_ENV=production
REDIS_CLOUD_PASSWORD=6PWsqLAGbRksFAg9DdHRU40zlRU32tOp:

COPY package.json /usr/local/app

RUN npm install -g nodemon

RUN npm install && npm chace clean --force

WORKDIR /usr/local/app/code

COPY . ./

CMD ["npm","run","start"]